services:
  - type: web
    name: nai-tiaras
    runtime: docker
    plan: 0.5c-512mb
    disk:
      name: nai-tiaras-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: NAI_ADMIN_EMAIL
        sync: false
      - key: NAI_ADMIN_PASSWORD
        sync: false
