import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, Check, Heart, Instagram, LockKeyhole, LogOut, MapPin, Menu, MessageCircle, Minus, Package, Pencil, Plus, Search, Send, ShoppingBag, Trash2, Truck, UserRound, X } from 'lucide-react'
import { PRODUCTS as FALLBACK_PRODUCTS, WHATSAPP, buildWhatsAppLink, COMPANY } from './data/content'

const CATEGORY_OPTIONS = ['Todos', 'Laços', 'Tiaras', 'Tiras de recém-nascido']
const HOME_PRODUCT_LIMIT = 6
const CATALOG_PAGE_SIZE = 10
const API = import.meta.env.VITE_API_URL || '/api'
const money = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
const unitLabel = (value) => ({ unidade: 'unidade', par: 'par', kit: 'kit' }[value] || value)

function initialProducts() {
  return FALLBACK_PRODUCTS.map((product, index) => ({
    ...product,
    name: product.name || product.title,
    description: product.description || '',
    category: index === 5 ? 'Tiaras' : index === 0 || index === 3 ? 'Tiras de recém-nascido' : 'Laços',
    price: [24.9, 32.9, 29.9, 19.9, 22.9, 34.9][index],
    sale_unit: index === 1 || index === 2 ? 'kit' : index === 4 ? 'par' : 'unidade',
    stock: [8, 6, 10, 12, 7, 5][index], status: 'active', featured: index < 3 || index === 5, available: true,
  }))
}

function readCart() { try { return JSON.parse(localStorage.getItem('nai-cart') || '[]') } catch { return [] } }
function screenFromHash() {
  if (window.location.hash === '#admin') return 'admin'
  if (window.location.hash === '#produtos') return 'products'
  return 'home'
}

export default function App() {
  const [products, setProducts] = useState(initialProducts)
  const [screen, setScreen] = useState(screenFromHash)
  const [category, setCategory] = useState('Todos')
  const [search, setSearch] = useState('')
  const [productPage, setProductPage] = useState(1)
  const [cart, setCart] = useState(readCart)
  const [cartOpen, setCartOpen] = useState(false)
  const [selected, setSelected] = useState(null)
  const [checkoutOpen, setCheckoutOpen] = useState(false)
  const [toast, setToast] = useState('')
  const [mobileMenu, setMobileMenu] = useState(false)

  useEffect(() => {
    fetch(`${API}/products`).then((r) => r.ok ? r.json() : Promise.reject()).then((data) => data.products?.length && setProducts(data.products)).catch(() => {})
  }, [])
  useEffect(() => { localStorage.setItem('nai-cart', JSON.stringify(cart)) }, [cart])
  useEffect(() => { const handler = () => setScreen(screenFromHash()); window.addEventListener('hashchange', handler); return () => window.removeEventListener('hashchange', handler) }, [])

  const filtered = useMemo(() => products.filter((item) => (category === 'Todos' || item.category === category) && String(item.name || item.title || '').toLowerCase().includes(search.toLowerCase())), [products, category, search])
  const homeProducts = useMemo(() => products.filter((item) => item.status !== 'inactive').slice(0, HOME_PRODUCT_LIMIT), [products])
  const totalPages = Math.max(1, Math.ceil(filtered.length / CATALOG_PAGE_SIZE))
  const pagedProducts = useMemo(() => filtered.slice((productPage - 1) * CATALOG_PAGE_SIZE, productPage * CATALOG_PAGE_SIZE), [filtered, productPage])
  const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0)
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2600) }
  const goToSection = (id) => { setMobileMenu(false); window.location.hash = id; window.setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }), 40) }
  const goToShop = (next = 'Todos') => { setCategory(next); setSearch(''); setProductPage(1); setMobileMenu(false); window.location.hash = 'produtos' }

  useEffect(() => { setProductPage((current) => Math.min(current, totalPages)) }, [totalPages])
  useEffect(() => { setProductPage(1) }, [category, search])

  function addToCart(item, quantity = 1) {
    if (!item.available || item.status !== 'active' || item.stock < 1) return notify('Este produto está indisponível no momento.')
    setCart((current) => { const found = current.find((entry) => entry.id === item.id); const next = (found?.quantity || 0) + quantity; if (next > item.stock) { notify(`Há apenas ${item.stock} ${unitLabel(item.sale_unit)}(s) disponíveis.`); return current }; return found ? current.map((entry) => entry.id === item.id ? { ...entry, quantity: next } : entry) : [...current, { ...item, quantity }] })
    setSelected(null); setCartOpen(true); notify('Produto adicionado ao carrinho.')
  }
  function changeQuantity(id, delta) { setCart((current) => current.map((item) => { if (item.id !== id) return item; const source = products.find((entry) => entry.id === id) || item; return { ...item, quantity: Math.max(1, Math.min(source.stock, item.quantity + delta)) } })) }
  function removeFromCart(id) { setCart((current) => current.filter((item) => item.id !== id)) }

  if (screen === 'admin') return <AdminWorkspace products={products} setProducts={setProducts} onBack={() => { window.location.hash = ''; setScreen('home') }} />

  return <div className="min-h-screen bg-[#fffafc] text-[#4a1226]">
    <header className="site-header"><div className="shell header-inner"><a className="brand" href="#inicio" onClick={(event) => { event.preventDefault(); goToSection('inicio') }}><img src="/assets/logo.png" alt="Nai Tiaras" /><span><strong>Nai</strong> Tiaras</span></a><nav className={`main-nav ${mobileMenu ? 'is-open' : ''}`}><a href="#inicio" onClick={(event) => { event.preventDefault(); goToSection('inicio') }}>Início</a><a href="#produtos" onClick={(event) => { event.preventDefault(); goToShop() }}>Produtos</a><a href="#sobre" onClick={(event) => { event.preventDefault(); goToSection('sobre') }}>Nossa história</a><a href="#contato" onClick={(event) => { event.preventDefault(); goToSection('contato') }}>Contato</a></nav><div className="header-actions"><button className="icon-button cart-trigger" onClick={() => setCartOpen(true)} aria-label="Abrir carrinho"><ShoppingBag size={21} />{cartCount > 0 && <span>{cartCount}</span>}</button><a className="header-whatsapp" href={buildWhatsAppLink()} target="_blank" rel="noreferrer">Fale conosco</a><button className="menu-trigger" onClick={() => setMobileMenu((value) => !value)} aria-label="Abrir menu"><Menu size={22} /></button></div></div></header>
    <main>
      {screen === 'products' ? <ProductsPage filtered={filtered} pagedProducts={pagedProducts} category={category} onCategoryChange={(next) => { setCategory(next); setProductPage(1) }} search={search} onSearchChange={(next) => { setSearch(next); setProductPage(1) }} page={productPage} totalPages={totalPages} onPageChange={setProductPage} onBack={() => goToSection('inicio')} onOpen={setSelected} onAdd={addToCart} /> : <>
      <section id="inicio" className="hero-section"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow"><span>✦</span> Acessórios artesanais desde 2015</div><h1>Pequenos detalhes.<br /><em>Grandes encantos.</em></h1><p>Laços, tiaras e faixas feitos à mão para acompanhar os momentos mais especiais da sua princesa.</p><div className="hero-actions"><button className="primary-button" onClick={() => goToShop()}>Ver coleção <ArrowRight size={17} /></button><a className="text-link" href={buildWhatsAppLink()} target="_blank" rel="noreferrer">Falar no WhatsApp <ArrowRight size={15} /></a></div><div className="hero-note"><span>♡</span> Feito com carinho em Recife</div></div><div className="hero-art"><div className="hero-card hero-card-back"><img src="/assets/produto-2.jpeg" alt="Laços artesanais" /></div><div className="hero-card hero-card-front"><img src="/assets/produto-4.jpeg" alt="Faixa infantil delicada" /></div><div className="hero-sticker"><Heart size={16} fill="currentColor" /> feito à mão</div></div></div></section>
      <section className="category-strip"><div className="shell category-row"><div><span className="section-kicker">Escolha por categoria</span><h2>Um toque especial para cada momento.</h2></div><div className="category-pills">{CATEGORY_OPTIONS.slice(1).map((item) => <button key={item} onClick={() => goToShop(item)}>{item}<ArrowRight size={15} /></button>)}</div></div></section>
      <section id="produtos" className="products-section shell"><div className="section-heading"><div><span className="section-kicker">Nossa vitrine</span><h2>Feitos para encantar</h2></div><p>Escolha seus favoritos, monte seu carrinho e finalize o pedido direto pelo WhatsApp.</p></div><div className="products-grid">{homeProducts.map((item) => <ProductCard key={item.id} product={item} onOpen={() => setSelected(item)} onAdd={() => addToCart(item)} />)}</div><div className="catalog-cta"><span>Mostrando {HOME_PRODUCT_LIMIT} produtos em destaque</span><button className="primary-button" onClick={() => goToShop()}>Ver todos os produtos <ArrowRight size={17} /></button></div></section>
      <section id="sobre" className="about-section"><div className="shell about-grid"><div className="about-image"><img src="/assets/produto-6.jpeg" alt="Tiara artesanal Nai Tiaras" /><div className="about-badge"><Heart size={18} fill="currentColor" /> carinho em cada detalhe</div></div><div className="about-copy"><span className="section-kicker">Nossa história</span><h2>Um laço de cada vez, desde 2015.</h2><p>A Nai Tiaras nasceu de um sonho simples: transformar fitas, rendas e muito amor em acessórios que fazem meninas e bebês se sentirem especiais.</p><p>Cada peça é montada à mão, com atenção ao acabamento e ao conforto. O mesmo cuidado do primeiro laço continua presente em cada pedido.</p><div className="stats"><div><strong>2015</strong><span>Fundação</span></div><div><strong>100%</strong><span>Artesanal</span></div><div><strong>+10</strong><span>Anos de carinho</span></div></div></div></div></section>
      <section className="service-section"><div className="shell service-grid"><div><span className="section-kicker">Para você comprar com tranquilidade</span><h2>Do nosso ateliê para a sua princesa.</h2></div><div className="service-list"><div><Package size={21} /><span><strong>Produtos artesanais</strong><small>Peças feitas com cuidado e acabamento delicado.</small></span></div><div><Truck size={21} /><span><strong>Retire ou receba em casa</strong><small>Entrega própria a partir de R$ 7,00 em Recife.</small></span></div><div><LockKeyhole size={21} /><span><strong>Pedido pelo WhatsApp</strong><small>Converse com a gente antes de confirmar.</small></span></div></div></div></section>
      </>}
    </main>
    <footer id="contato" className="site-footer"><div className="shell footer-grid"><div><div className="footer-brand"><img src="/assets/logo.png" alt="Nai Tiaras" /><span>Nai Tiaras</span></div><p>{COMPANY.slogan}. Acessórios feitos com carinho para encantar.</p></div><div><h3>Visite a gente</h3><p className="footer-contact"><MapPin size={16} /> R. Adolfo Caminha, 244<br />Córrego do Jenipapo, Recife - PE</p></div><div><h3>Fale conosco</h3><a className="footer-contact" href={buildWhatsAppLink()} target="_blank" rel="noreferrer"><UserRound size={16} /> {WHATSAPP.displayNumber}</a><a className="footer-contact" href="#"><Instagram size={16} /> @naitiaras</a></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} Nai Tiaras</span><a href="#admin" className="admin-link">Acesso da gestão</a></div></footer>
    {cartOpen && <CartDrawer cart={cart} subtotal={subtotal} onClose={() => setCartOpen(false)} onChange={changeQuantity} onRemove={removeFromCart} onCheckout={() => { setCartOpen(false); setCheckoutOpen(true) }} />}{selected && <ProductModal product={selected} onClose={() => setSelected(null)} onAdd={addToCart} />}{checkoutOpen && <CheckoutModalFixed cart={cart} subtotal={subtotal} onClose={() => setCheckoutOpen(false)} onSuccess={() => { setCart([]); setCheckoutOpen(false); notify('Pedido criado. O WhatsApp será aberto agora.') }} />}{toast && <div className="toast"><Check size={17} /> {toast}</div>}<ChatWidget />
  </div>
}

function ProductsPage({ filtered, pagedProducts, category, onCategoryChange, search, onSearchChange, page, totalPages, onPageChange, onBack, onOpen, onAdd }) {
  return <section className="products-page">
    <div className="shell products-page-head">
      <button className="back-link" onClick={onBack}><ArrowRight size={16} className="back-arrow" /> Voltar para início</button>
      <span className="section-kicker">Catálogo completo</span>
      <h1>Encontre o acessório perfeito.</h1>
      <p>{filtered.length} {filtered.length === 1 ? 'produto disponível' : 'produtos disponíveis'} para você escolher com calma.</p>
    </div>
    <div className="products-section shell products-page-content">
      <div className="catalog-toolbar">
        <div className="category-tabs">{CATEGORY_OPTIONS.map((item) => <button className={category === item ? 'active' : ''} key={item} onClick={() => onCategoryChange(item)}>{item}</button>)}</div>
        <label className="search-box"><Search size={17} /><input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Buscar produto" /></label>
      </div>
      <div className="products-grid">{pagedProducts.map((item) => <ProductCard key={item.id} product={item} onOpen={() => onOpen(item)} onAdd={() => onAdd(item)} />)}</div>
      {filtered.length === 0 && <div className="empty-state"><Package size={30} /><h3>Nenhum produto encontrado</h3><p>Tente buscar por outro nome ou categoria.</p></div>}
      {filtered.length > 0 && <div className="pagination" aria-label="Paginação de produtos"><button onClick={() => onPageChange(page - 1)} disabled={page === 1}>Anterior</button><div className="pagination-pages">{Array.from({ length: totalPages }, (_, index) => index + 1).map((number) => <button key={number} className={page === number ? 'active' : ''} onClick={() => onPageChange(number)} aria-label={`Ir para página ${number}`}>{number}</button>)}</div><button onClick={() => onPageChange(page + 1)} disabled={page === totalPages}>Próxima</button></div>}
    </div>
  </section>
}

function ChatWidget() {
  const [open, setOpen] = useState(false)
  const [welcome, setWelcome] = useState(true)
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [messages, setMessages] = useState([{ role: 'assistant', content: 'Olá! Posso ajudar com produtos, preços, estoque, retirada ou entrega.' }])
  async function sendMessage(event) {
    event.preventDefault()
    const content = input.trim()
    if (!content || loading) return
    const next = [...messages, { role: 'user', content }]
    setMessages(next); setInput(''); setLoading(true)
    try {
      const response = await fetch(`${API}/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: next }) })
      const data = await response.json()
      setMessages((current) => [...current, { role: 'assistant', content: response.ok ? data.reply : 'No momento não consegui responder. Você pode falar conosco pelo WhatsApp.' }])
    } catch { setMessages((current) => [...current, { role: 'assistant', content: 'Não consegui conectar ao atendimento agora. Fale conosco pelo WhatsApp para receber ajuda.' }]) }
    setLoading(false)
  }
  return <><button className={`chat-launcher ${open ? 'is-open' : ''}`} onClick={() => { setOpen((value) => !value); setWelcome(false) }} aria-label="Abrir atendimento"><MessageCircle size={24} />{!open && <span className="chat-dot" />}</button>{!open && welcome && <button className="chat-welcome" onClick={() => { setOpen(true); setWelcome(false) }}>Olá! Posso ajudar você com produtos, preços e pedidos.<span>×</span></button>}{open && <section className="chat-panel" aria-label="Atendimento virtual"><header><div><strong>Atendimento Nai</strong><small>Online para ajudar</small></div><button onClick={() => setOpen(false)} aria-label="Fechar atendimento"><X size={18} /></button></header><div className="chat-messages">{messages.map((message, index) => <div className={`chat-message ${message.role}`} key={`${message.role}-${index}`}>{message.content}</div>)}{loading && <div className="chat-message assistant typing">Digitando...</div>}</div><form onSubmit={sendMessage}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Escreva sua dúvida..." aria-label="Mensagem para o atendimento" /><button disabled={loading || !input.trim()} aria-label="Enviar mensagem"><Send size={17} /></button></form></section>}</>
}

function ProductCard({ product, onOpen, onAdd }) { return <article className="product-card"><button className="product-image" onClick={onOpen} aria-label={`Ver ${product.name}`}><img src={product.image} alt={product.name} />{product.featured && <span className="product-tag">Favorito</span>}{product.stock < 1 && <span className="sold-out">Indisponível</span>}</button><div className="product-body"><span className="product-category">{product.category}</span><button className="product-name" onClick={onOpen}>{product.name}</button><p>{product.description}</p><div className="product-footer"><div><strong>{money(product.price)}</strong><small> / {unitLabel(product.sale_unit)}</small></div><button className="add-button" onClick={onAdd} disabled={!product.available || product.stock < 1} aria-label={`Adicionar ${product.name}`}><Plus size={18} /></button></div></div></article> }

function CartDrawer({ cart, subtotal, onClose, onChange, onRemove, onCheckout }) { return <div className="overlay" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><aside className="cart-drawer"><div className="drawer-head"><div><span className="section-kicker">Seu pedido</span><h2>Carrinho <small>({cart.length})</small></h2></div><button className="close-button" onClick={onClose}><X size={21} /></button></div>{cart.length === 0 ? <div className="drawer-empty"><ShoppingBag size={38} /><h3>Seu carrinho está vazio</h3><p>Adicione seus favoritos para começar.</p></div> : <><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div className="cart-item-info"><strong>{item.name}</strong><small>{money(item.price)} / {unitLabel(item.sale_unit)}</small><div className="quantity-control"><button onClick={() => onChange(item.id, -1)}><Minus size={13} /></button><span>{item.quantity}</span><button onClick={() => onChange(item.id, 1)}><Plus size={13} /></button></div></div><div className="cart-item-right"><strong>{money(item.price * item.quantity)}</strong><button onClick={() => onRemove(item.id)} aria-label="Remover item"><Trash2 size={15} /></button></div></div>)}</div><div className="drawer-summary"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p>Entrega calculada na finalização. Retirada na loja é gratuita.</p><button className="primary-button full-button" onClick={onCheckout}>Continuar pedido <ArrowRight size={17} /></button></div></>}</aside></div> }

function ProductModal({ product, onClose, onAdd }) { const [quantity, setQuantity] = useState(1); return <div className="overlay"><div className="product-modal"><button className="close-button modal-close" onClick={onClose}><X size={21} /></button><div className="modal-image"><img src={product.image} alt={product.name} /></div><div className="modal-content"><span className="product-category">{product.category}</span><h2>{product.name}</h2><p>{product.description}</p><div className="details-row"><span>Disponibilidade</span><strong>{product.stock} {unitLabel(product.sale_unit)}(s)</strong></div><div className="details-row"><span>Valor</span><strong className="modal-price">{money(product.price)} <small>/ {unitLabel(product.sale_unit)}</small></strong></div><div className="modal-actions"><div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus size={14} /></button><span>{quantity}</span><button onClick={() => setQuantity(Math.min(product.stock, quantity + 1))}><Plus size={14} /></button></div><button className="primary-button" onClick={() => onAdd(product, quantity)} disabled={!product.available}>Adicionar ao carrinho</button></div></div></div></div> }

function CheckoutModalFixed({ cart, subtotal, onClose, onSuccess }) {
  const [form, setForm] = useState({ name: '', phone: '', delivery: 'pickup', address: '', notes: '' })
  const [sending, setSending] = useState(false)
  const [error, setError] = useState('')
  const deliveryFee = form.delivery === 'delivery' ? 7 : 0
  const total = subtotal + deliveryFee
  const update = (key, value) => { setError(''); setForm((current) => ({ ...current, [key]: value })) }

  async function finish(event) {
    event.preventDefault()
    setSending(true); setError('')
    const popup = window.open('', '_blank')
    const payload = { customer: { name: form.name, phone: form.phone }, delivery_method: form.delivery, delivery_address: form.address, notes: form.notes, items: cart.map((item) => ({ id: item.id, quantity: item.quantity })) }
    try {
      const response = await fetch(`${API}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
      const result = await response.json()
      if (!response.ok) throw new Error(result.error || 'Não foi possível registrar o pedido.')
      const serverItems = result.items || cart.map((item) => ({ name: item.name, sale_unit: item.sale_unit, quantity: item.quantity, subtotal: item.price * item.quantity }))
      const lines = serverItems.map((item) => `- ${item.quantity} ${unitLabel(item.sale_unit)}(s) de ${item.name} — ${money(item.subtotal)}`).join('\n')
      const delivery = form.delivery === 'delivery' ? `Entrega própria — ${money(result.delivery_fee)}\nEndereço: ${form.address}` : 'Retirada na loja — sem taxa'
      const message = `Olá! Gostaria de fazer um pedido na Nai Tiaras.\n\nPedido: #${result.order_number}\n\n${lines}\n\nSubtotal: ${money(result.subtotal)}\n${delivery}\nTotal: ${money(result.total)}\n\nNome: ${form.name}\nTelefone: ${form.phone}${form.notes ? `\nObservações: ${form.notes}` : ''}\n\nAguardo a confirmação da disponibilidade. Obrigada!`
      const url = buildWhatsAppLink(message)
      if (popup) popup.location.href = url
      else window.location.href = url
      onSuccess()
    } catch (reason) {
      if (popup) popup.close()
      setError(reason.message || 'Não foi possível registrar o pedido. Tente novamente.')
    } finally { setSending(false) }
  }

  return <div className="overlay"><div className="checkout-modal"><div className="drawer-head"><div><span className="section-kicker">Último passo</span><h2>Finalizar pedido</h2></div><button className="close-button" onClick={onClose}><X size={21} /></button></div><form onSubmit={finish}><div className="form-grid"><label>Seu nome<input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Como podemos chamar você?" /></label><label>WhatsApp<input required value={form.phone} onChange={(event) => update('phone', event.target.value)} placeholder="(81) 99999-9999" /></label></div><fieldset><legend>Como deseja receber?</legend><label className="choice"><input type="radio" checked={form.delivery === 'pickup'} onChange={() => update('delivery', 'pickup')} /><span><strong>Retirar na loja</strong><small>R. Adolfo Caminha, 244 — Córrego do Jenipapo</small></span></label><label className="choice"><input type="radio" checked={form.delivery === 'delivery'} onChange={() => update('delivery', 'delivery')} /><span><strong>Entrega pela Nai Tiaras <em>a partir de R$ 7,00</em></strong><small>O valor final será confirmado pelo WhatsApp</small></span></label></fieldset>{form.delivery === 'delivery' && <label>Endereço completo<textarea required value={form.address} onChange={(event) => update('address', event.target.value)} placeholder="Rua, número, bairro e ponto de referência" /></label>}<label>Observações <span className="optional">opcional</span><textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} placeholder="Cor, tamanho ou algum detalhe do pedido" /></label>{error && <div className="form-error">{error}</div>}<div className="checkout-total"><span>Total do pedido<strong>{money(total)}</strong></span><button className="primary-button" disabled={sending}>{sending ? 'Registrando...' : <>Abrir WhatsApp <ArrowRight size={17} /></>}</button></div></form></div></div>
}

function CheckoutModal({ cart, subtotal, onClose, onSuccess }) {
  const [form, setForm] = useState({ name: '', phone: '', delivery: 'pickup', address: '', notes: '' }); const [sending, setSending] = useState(false); const deliveryFee = form.delivery === 'delivery' ? 7 : 0; const total = subtotal + deliveryFee; const update = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  async function finish(event) { event.preventDefault(); setSending(true); const payload = { customer: { name: form.name, phone: form.phone }, delivery_method: form.delivery, delivery_address: form.address, notes: form.notes, items: cart.map((item) => ({ id: item.id, quantity: item.quantity })) }; let orderNumber = `LOCAL-${Date.now().toString().slice(-6)}`; try { const response = await fetch(`${API}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (response.ok) orderNumber = result.order_number } catch {} const lines = cart.map((item) => `- ${item.quantity} ${unitLabel(item.sale_unit)}(s) de ${item.name} — ${money(item.price * item.quantity)}`).join('\n'); const delivery = form.delivery === 'delivery' ? `Entrega própria — ${money(deliveryFee)}\nEndereço: ${form.address}` : 'Retirada na loja — sem taxa'; const message = `Olá! Gostaria de fazer um pedido na Nai Tiaras.\n\nPedido: #${orderNumber}\n\n${lines}\n\nSubtotal: ${money(subtotal)}\n${delivery}\nTotal: ${money(total)}\n\nNome: ${form.name}\nTelefone: ${form.phone}${form.notes ? `\nObservações: ${form.notes}` : ''}\n\nAguardo a confirmação da disponibilidade. Obrigada!`; window.open(buildWhatsAppLink(message), '_blank'); setSending(false); onSuccess() }
  return <div className="overlay"><div className="checkout-modal"><div className="drawer-head"><div><span className="section-kicker">Último passo</span><h2>Finalizar pedido</h2></div><button className="close-button" onClick={onClose}><X size={21} /></button></div><form onSubmit={finish}><div className="form-grid"><label>Seu nome<input required value={form.name} onChange={(event) => update('name', event.target.value)} placeholder="Como podemos chamar você?" /></label><label>WhatsApp<input required value={form.phone} onChange={(event) => update('phone', event.target.value)} placeholder="(81) 99999-9999" /></label></div><fieldset><legend>Como deseja receber?</legend><label className="choice"><input type="radio" checked={form.delivery === 'pickup'} onChange={() => update('delivery', 'pickup')} /><span><strong>Retirar na loja</strong><small>R. Adolfo Caminha, 244 — Córrego do Jenipapo</small></span></label><label className="choice"><input type="radio" checked={form.delivery === 'delivery'} onChange={() => update('delivery', 'delivery')} /><span><strong>Entrega pela Nai Tiaras <em>a partir de R$ 7,00</em></strong><small>O valor final será confirmado pelo WhatsApp</small></span></label></fieldset>{form.delivery === 'delivery' && <label>Endereço completo<textarea required value={form.address} onChange={(event) => update('address', event.target.value)} placeholder="Rua, número, bairro e ponto de referência" /></label>}<label>Observações <span className="optional">opcional</span><textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} placeholder="Cor, tamanho ou algum detalhe do pedido" /></label><div className="checkout-total"><span>Total do pedido<strong>{money(total)}</strong></span><button className="primary-button" disabled={sending}>{sending ? 'Enviando...' : <>Abrir WhatsApp <ArrowRight size={17} /></>}</button></div></form></div></div>
}

function AdminWorkspace({ products, setProducts, onBack }) {
  const [token, setToken] = useState(() => localStorage.getItem('nai-admin-token') || '')
  const [orders, setOrders] = useState([])
  const [view, setView] = useState('overview')
  const [form, setForm] = useState(null)
  const [selectedOrder, setSelectedOrder] = useState(null)
  const [note, setNote] = useState('')
  const [login, setLogin] = useState({ email: 'admin@naitiaras.com', password: '' })
  const [message, setMessage] = useState('')
  const [query, setQuery] = useState('')
  const nav = [{ id: 'overview', label: 'Visão geral', icon: '⌂' }, { id: 'stock', label: 'Controle de estoque', icon: '▣' }, { id: 'sales', label: 'Vendas e pedidos', icon: '↗' }, { id: 'notes', label: 'Anotações', icon: '✎' }]
  const statusLabel = { pending_contact: 'Aguardando contato', awaiting_confirmation: 'Aguardando confirmação', confirmed: 'Confirmado', preparing: 'Em produção', ready: 'Pronto para entrega', completed: 'Concluído', canceled: 'Cancelado' }

  async function loadOrders() { if (!token) return; const response = await fetch(`${API}/admin/orders`, { credentials: 'include' }); if (response.status === 401) { localStorage.removeItem('nai-admin-token'); setToken(''); setMessage('Sua sessão expirou. Entre novamente para visualizar os pedidos.'); return } if (response.ok) setOrders((await response.json()).orders || []) }
  useEffect(() => { loadOrders().catch(() => setMessage('Não foi possível carregar os pedidos.')) }, [token])
  async function signIn(event) { event.preventDefault(); setMessage(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); localStorage.removeItem('nai-admin-token'); setToken('cookie') } catch (error) { setMessage(error.message || 'Não foi possível entrar.') } }
  async function logout() { await fetch(`${API}/auth/logout`, { method: 'POST', credentials: 'include' }).catch(() => {}); localStorage.removeItem('nai-admin-token'); setToken('') }
  function updateForm(key, value) { setForm((current) => ({ ...current, [key]: value })) }
  async function saveProduct(event) { event.preventDefault(); const body = { ...form, price: Number(form.price), stock: Number(form.stock), featured: Boolean(form.featured), status: form.status || 'active' }; const response = await fetch(form.id ? `${API}/admin/products/${form.id}` : `${API}/admin/products`, { method: form.id ? 'PATCH' : 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Não foi possível salvar o produto.'); setProducts((current) => form.id ? current.map((item) => item.id === data.product.id ? data.product : item) : [data.product, ...current]); setForm(null); setMessage('Produto salvo com sucesso.') }
  async function updateOrder(orderId, values) { const response = await fetch(`${API}/admin/orders/${orderId}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); const data = await response.json().catch(() => ({})); if (!response.ok) return setMessage(data.error || 'Não foi possível atualizar o pedido.'); setOrders((current) => current.map((order) => order.id === orderId ? { ...order, ...values } : order)); if (values.status && ['confirmed', 'preparing', 'ready', 'completed'].includes(values.status)) fetch(`${API}/products`).then((result) => result.ok ? result.json() : Promise.reject()).then((result) => setProducts(result.products || [])).catch(() => {}); setMessage('Pedido atualizado.') }
  function openNotes(order) { setSelectedOrder(order); setNote(order.admin_notes || '') }
  const active = products.filter((item) => item.status === 'active'); const lowStock = active.filter((item) => Number(item.stock) <= 3); const pending = orders.filter((order) => ['pending_contact', 'awaiting_confirmation'].includes(order.status)); const confirmed = orders.filter((order) => ['confirmed', 'preparing', 'ready', 'completed'].includes(order.status)); const revenue = confirmed.reduce((sum, order) => sum + Number(order.total || 0), 0); const visibleProducts = products.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase()))
  const monthData = Array.from({ length: 6 }, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index)); const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`; return { key, label: date.toLocaleDateString('pt-BR', { month: 'short' }).replace('.', ''), total: orders.filter((order) => order.created_at?.startsWith(key) && order.status !== 'canceled').reduce((sum, order) => sum + Number(order.total || 0), 0) } }); const maxMonth = Math.max(...monthData.map((item) => item.total), 1)
  if (!token) return <div className="admin-page"><div className="admin-login"><button className="back-link" onClick={onBack}>← Voltar para a loja</button><div className="admin-logo"><img src="/assets/logo.png" alt="Nai Tiaras" /></div><span className="section-kicker">Área restrita</span><h1>Gestão da loja</h1><p>Acesso exclusivo para a equipe da Nai Tiaras.</p><form onSubmit={signIn}><label>E-mail<input type="email" value={login.email} onChange={(event) => setLogin({ ...login, email: event.target.value })} required /></label><label>Senha<input type="password" value={login.password} onChange={(event) => setLogin({ ...login, password: event.target.value })} required /></label>{message && <div className="form-error">{message}</div>}<button className="primary-button full-button">Entrar <ArrowRight size={17} /></button></form></div></div>
  return <div className="admin-workspace"><aside className="admin-sidebar"><a className="sidebar-brand" href="#inicio"><img src="/assets/logo.png" alt="Nai Tiaras" /><span><strong>Nai</strong> Tiaras<small>gestão</small></span></a><div className="sidebar-label">Menu principal</div><nav className="sidebar-menu">{nav.map((item) => <button key={item.id} className={view === item.id ? 'active' : ''} onClick={() => setView(item.id)}><span>{item.icon}</span>{item.label}{item.id === 'sales' && pending.length > 0 && <b>{pending.length}</b>}</button>)}</nav><div className="sidebar-bottom"><button onClick={() => setForm({ name: '', category: 'Laços', description: '', price: 0, sale_unit: 'unidade', stock: 0, image: '', status: 'active', featured: false })}><Plus size={16} /> Novo produto</button><button onClick={onBack}>Ver loja</button><button onClick={logout}><LogOut size={16} /> Sair</button></div></aside><main className="admin-content"><header className="admin-topbar"><div><span className="section-kicker">Painel administrativo</span><h1>{nav.find((item) => item.id === view)?.label}</h1></div><div className="admin-user"><span>Gestão Nai Tiaras</span><button onClick={() => loadOrders()}>Atualizar</button></div></header>{message && <div className="form-success">{message}</div>}
    {view === 'overview' && <><div className="insight-cards"><div><span className="insight-icon">R$</span><small>Vendas confirmadas</small><strong>{money(revenue)}</strong><em>{confirmed.length} pedidos</em></div><div><span className="insight-icon pink">↗</span><small>Pedidos pendentes</small><strong>{pending.length}</strong><em>Precisam de atenção</em></div><div><span className="insight-icon gold">▣</span><small>Produtos ativos</small><strong>{active.length}</strong><em>{lowStock.length} com estoque baixo</em></div><div><span className="insight-icon green">✓</span><small>Ticket médio</small><strong>{money(confirmed.length ? revenue / confirmed.length : 0)}</strong><em>Pedidos confirmados</em></div></div><div className="insight-grid"><section className="insight-card"><div className="insight-card-title"><div><span className="section-kicker">Desempenho</span><h2>Vendas por mês</h2></div><span>últimos 6 meses</span></div><div className="sales-chart">{monthData.map((item) => <div className="chart-column" key={item.key}><strong>{item.total ? money(item.total).replace(',00', '') : '—'}</strong><div className="chart-bar-wrap"><div className="chart-bar" style={{ height: `${Math.max(7, (item.total / maxMonth) * 100)}%` }} /></div><small>{item.label}</small></div>)}</div></section><section className="insight-card"><div className="insight-card-title"><div><span className="section-kicker">Atenção</span><h2>Estoque baixo</h2></div><button className="small-action" onClick={() => setView('stock')}>Ver estoque <ArrowRight size={14} /></button></div>{lowStock.length === 0 ? <div className="admin-empty"><Check size={25} /><p>Nenhum produto precisa de reposição.</p></div> : <div className="low-stock-list">{lowStock.slice(0, 5).map((item) => <div key={item.id}><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{item.category}</small></span><b>{item.stock} {unitLabel(item.sale_unit)}(s)</b></div>)}</div>}</section></div><section className="insight-card recent-card"><div className="insight-card-title"><div><span className="section-kicker">Atendimento</span><h2>Últimas vendas</h2></div><button className="small-action" onClick={() => setView('sales')}>Ver vendas <ArrowRight size={14} /></button></div>{orders.length === 0 ? <div className="admin-empty"><ShoppingBag size={25} /><p>As vendas feitas pelo site aparecerão aqui.</p></div> : <div className="recent-sales">{orders.slice(0, 6).map((order) => <div key={order.id}><span><strong>#{order.order_number}</strong><small>{order.customer_name} · {new Date(order.created_at).toLocaleDateString('pt-BR')}</small></span><b>{money(order.total)}</b><select value={order.status} onChange={(event) => updateOrder(order.id, { status: event.target.value })}>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>)}</div>}</section></>}
    {view === 'stock' && <section className="insight-card full-admin-card"><div className="insight-card-title"><div><span className="section-kicker">Inventário</span><h2>Controle de estoque</h2><p className="panel-description">Acompanhe o que está disponível e identifique rapidamente o que precisa ser reposto.</p></div><label className="search-box admin-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar produto" /></label></div><div className="inventory-table"><div className="inventory-head"><span>Produto</span><span>Categoria</span><span>Unidade</span><span>Estoque</span><span>Situação</span><span /></div>{visibleProducts.map((item) => <div className="inventory-row" key={item.id}><div className="inventory-product"><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{money(item.price)}</small></span></div><span>{item.category}</span><span>{unitLabel(item.sale_unit)}</span><b className={item.stock <= 3 ? 'stock-out' : 'stock-ok'}>{item.stock}</b><span className={item.stock <= 3 ? 'status-inactive' : 'status-active'}>{item.stock <= 3 ? 'Repor em breve' : 'Em dia'}</span><button onClick={() => setForm({ ...item })} aria-label={`Editar ${item.name}`}><Pencil size={16} /></button></div>)}</div></section>}
    {view === 'sales' && <section className="insight-card full-admin-card"><div className="insight-card-title"><div><span className="section-kicker">Histórico</span><h2>Vendas e pedidos</h2><p className="panel-description">Atualize o andamento de cada pedido e registre observações internas.</p></div><strong className="sales-total">{money(revenue)} confirmados</strong></div><div className="sales-list">{orders.length === 0 ? <div className="admin-empty"><ShoppingBag size={25} /><p>Nenhuma venda registrada ainda.</p></div> : orders.map((order) => <div className="sale-row" key={order.id}><div><strong>#{order.order_number}</strong><small>{order.customer_name} · {order.customer_phone}</small></div><span>{new Date(order.created_at).toLocaleDateString('pt-BR')}</span><strong>{money(order.total)}</strong><select value={order.status} onChange={(event) => updateOrder(order.id, { status: event.target.value })}>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><button className="note-button" onClick={() => { openNotes(order); setView('notes') }}>Anotar</button></div>)}</div></section>}
    {view === 'notes' && <section className="notes-layout"><div className="insight-card notes-orders"><div className="insight-card-title"><div><span className="section-kicker">Registro interno</span><h2>Anotações das vendas</h2></div></div>{orders.length === 0 ? <div className="admin-empty"><p>Nenhuma venda para anotar.</p></div> : <div className="notes-order-list">{orders.map((order) => <button className={selectedOrder?.id === order.id ? 'active' : ''} key={order.id} onClick={() => openNotes(order)}><span><strong>#{order.order_number}</strong><small>{order.customer_name}</small></span><b>{order.admin_notes ? 'Com anotação' : 'Sem anotação'}</b></button>)}</div>}</div><div className="insight-card note-editor">{selectedOrder ? <><span className="section-kicker">Pedido #{selectedOrder.order_number}</span><h2>Anotação interna</h2><p>Use este espaço para registrar pagamento, combinação de retirada, personalização ou qualquer detalhe importante.</p><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Escreva uma anotação para a equipe..." /><button className="primary-button" onClick={() => updateOrder(selectedOrder.id, { admin_notes: note })}>Salvar anotação <Check size={17} /></button></> : <div className="admin-empty"><span className="note-large">✎</span><h2>Selecione uma venda</h2><p>As anotações ficam visíveis somente para a gestão.</p></div>}</div></section>}
  </main>{form && <ProductForm form={form} updateForm={updateForm} onClose={() => setForm(null)} onSave={saveProduct} />}</div>
}

function AdminDashboardPro({ products, setProducts, onBack }) {
  const [token, setToken] = useState(() => localStorage.getItem('nai-admin-token') || '')
  const [orders, setOrders] = useState([])
  const [view, setView] = useState('overview')
  const [form, setForm] = useState(null)
  const [login, setLogin] = useState({ email: 'admin@naitiaras.com', password: '' })
  const [query, setQuery] = useState('')
  const [message, setMessage] = useState('')

  async function loadOrders() {
    if (!token) return
    const response = await fetch(`${API}/admin/orders`, { headers: { Authorization: `Bearer ${token}` } })
    if (response.ok) setOrders((await response.json()).orders || [])
  }
  useEffect(() => { loadOrders().catch(() => setMessage('Não foi possível carregar os pedidos.')) }, [token])
  async function signIn(event) { event.preventDefault(); setMessage(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); localStorage.setItem('nai-admin-token', data.token); setToken(data.token) } catch (error) { setMessage(error.message || 'Não foi possível entrar. Verifique se o backend está ativo.') } }
  function logout() { localStorage.removeItem('nai-admin-token'); setToken('') }
  function updateForm(key, value) { setForm((current) => ({ ...current, [key]: value })) }
  async function saveProduct(event) { event.preventDefault(); const body = { ...form, price: Number(form.price), stock: Number(form.stock), featured: Boolean(form.featured), status: form.status || 'active' }; const response = await fetch(form.id ? `${API}/admin/products/${form.id}` : `${API}/admin/products`, { method: form.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Não foi possível salvar o produto.'); setProducts((current) => form.id ? current.map((item) => item.id === data.product.id ? data.product : item) : [data.product, ...current]); setForm(null); setMessage('Produto salvo com sucesso.') }
  async function changeOrderStatus(orderId, status) { const response = await fetch(`${API}/admin/orders/${orderId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ status }) }); if (response.ok) { setOrders((current) => current.map((order) => order.id === orderId ? { ...order, status } : order)); setMessage('Status do pedido atualizado.') } }
  if (!token) return <div className="admin-page"><div className="admin-login"><button className="back-link" onClick={onBack}>← Voltar para a loja</button><div className="admin-logo"><img src="/assets/logo.png" alt="Nai Tiaras" /></div><span className="section-kicker">Área restrita</span><h1>Gestão da loja</h1><p>Acesso exclusivo para a equipe da Nai Tiaras.</p><form onSubmit={signIn}><label>E-mail<input type="email" value={login.email} onChange={(event) => setLogin({ ...login, email: event.target.value })} required /></label><label>Senha<input type="password" value={login.password} onChange={(event) => setLogin({ ...login, password: event.target.value })} required /></label>{message && <div className="form-error">{message}</div>}<button className="primary-button full-button">Entrar <ArrowRight size={17} /></button></form></div></div>
  const activeProducts = products.filter((item) => item.status === 'active'); const lowStock = activeProducts.filter((item) => Number(item.stock) <= 3); const pendingOrders = orders.filter((order) => ['pending_contact', 'awaiting_confirmation'].includes(order.status)); const confirmedOrders = orders.filter((order) => ['confirmed', 'preparing', 'ready', 'completed'].includes(order.status)); const totalRevenue = confirmedOrders.reduce((sum, order) => sum + Number(order.total || 0), 0); const visibleProducts = products.filter((item) => `${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())); const statusLabel = { pending_contact: 'Aguardando contato', awaiting_confirmation: 'Aguardando confirmação', confirmed: 'Confirmado', preparing: 'Em produção', ready: 'Pronto para entrega', completed: 'Concluído', canceled: 'Cancelado' }
  return <div className="admin-page"><header className="admin-header"><div className="shell header-inner"><a className="brand" href="#inicio"><img src="/assets/logo.png" alt="Nai Tiaras" /><span><strong>Nai</strong> Tiaras <small>gestão</small></span></a><div className="admin-header-actions"><button onClick={onBack}>Ver loja</button><button onClick={logout}><LogOut size={17} /> Sair</button></div></div></header><main className="shell admin-main"><div className="admin-title"><div><span className="section-kicker">Painel administrativo</span><h1>Olá, gestão.</h1><p>Uma visão rápida do que precisa da sua atenção hoje.</p></div><button className="primary-button" onClick={() => setForm({ name: '', category: 'Laços', description: '', price: 0, sale_unit: 'unidade', stock: 0, image: '', status: 'active', featured: false })}><Plus size={17} /> Novo produto</button></div><nav className="admin-tabs"><button className={view === 'overview' ? 'active' : ''} onClick={() => setView('overview')}>Resumo</button><button className={view === 'products' ? 'active' : ''} onClick={() => setView('products')}>Catálogo <span>{products.length}</span></button><button className={view === 'orders' ? 'active' : ''} onClick={() => setView('orders')}>Pedidos <span>{pendingOrders.length}</span></button></nav>{message && <div className="form-success">{message}</div>}
    {view === 'overview' && <><div className="admin-stats"><div><Package size={19} /><span>Produtos ativos<strong>{activeProducts.length}</strong><small>{lowStock.length ? `${lowStock.length} com estoque baixo` : 'Estoque em dia'}</small></span></div><div><ShoppingBag size={19} /><span>Pedidos pendentes<strong>{pendingOrders.length}</strong><small>Precisam de atenção</small></span></div><div><Truck size={19} /><span>Pedidos confirmados<strong>{confirmedOrders.length}</strong><small>Em andamento ou concluídos</small></span></div><div><span className="stat-symbol">R$</span><span>Vendas confirmadas<strong>{money(totalRevenue)}</strong><small>Pedidos confirmados</small></span></div></div><div className="dashboard-grid"><section className="admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Acompanhe o fluxo</span><h2>Pedidos recentes</h2></div><button className="small-action" onClick={() => setView('orders')}>Ver todos <ArrowRight size={14} /></button></div>{orders.length === 0 ? <div className="admin-empty"><ShoppingBag size={25} /><p>Os pedidos feitos pelo site aparecerão aqui.</p></div> : <div className="orders-list">{orders.slice(0, 5).map((order) => <div className="order-row dashboard-order" key={order.id}><div><strong>#{order.order_number}</strong><small>{order.customer_name} · {money(order.total)}</small></div><select value={order.status} onChange={(event) => changeOrderStatus(order.id, event.target.value)}>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>)}</div>}</section><section className="admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Atenção</span><h2>Estoque baixo</h2></div><button className="small-action" onClick={() => setView('products')}>Gerenciar <ArrowRight size={14} /></button></div>{lowStock.length === 0 ? <div className="admin-empty"><Check size={25} /><p>Nenhum produto precisa de reposição agora.</p></div> : <div className="low-stock-list">{lowStock.map((item) => <div key={item.id}><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{item.category}</small></span><b>{item.stock} {unitLabel(item.sale_unit)}(s)</b></div>)}</div>}</section></div></>}
    {view === 'products' && <section className="admin-card full-admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Gestão do catálogo</span><h2>Produtos e estoque</h2></div><label className="search-box admin-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar produto" /></label></div><div className="inventory-table"><div className="inventory-head"><span>Produto</span><span>Categoria</span><span>Preço</span><span>Estoque</span><span>Status</span><span /></div>{visibleProducts.map((item) => <div className="inventory-row" key={item.id}><div className="inventory-product"><img src={item.image} alt="" /><span><strong>{item.name}</strong><small>{unitLabel(item.sale_unit)}</small></span></div><span>{item.category}</span><span>{money(item.price)}</span><b className={item.stock <= 3 ? 'stock-out' : 'stock-ok'}>{item.stock}</b><span className={item.status === 'active' ? 'status-active' : 'status-inactive'}>{item.status === 'active' ? 'Ativo' : 'Inativo'}</span><button onClick={() => setForm({ ...item })} aria-label={`Editar ${item.name}`}><Pencil size={16} /></button></div>)}</div></section>}
    {view === 'orders' && <section className="admin-card full-admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Atendimento</span><h2>Todos os pedidos</h2></div><button className="small-action" onClick={() => loadOrders()}>Atualizar <Check size={14} /></button></div><div className="inventory-table orders-table"><div className="inventory-head"><span>Pedido</span><span>Cliente</span><span>Data</span><span>Total</span><span>Status</span></div>{orders.length === 0 ? <div className="admin-empty"><ShoppingBag size={25} /><p>Nenhum pedido registrado ainda.</p></div> : orders.map((order) => <div className="inventory-row" key={order.id}><span><strong>#{order.order_number}</strong></span><span>{order.customer_name}<small>{order.customer_phone}</small></span><span>{new Date(order.created_at).toLocaleDateString('pt-BR')}</span><strong>{money(order.total)}</strong><select value={order.status} onChange={(event) => changeOrderStatus(order.id, event.target.value)}>{Object.entries(statusLabel).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div>)}</div></section>}
  </main>{form && <ProductForm form={form} updateForm={updateForm} onClose={() => setForm(null)} onSave={saveProduct} />}</div>
}

function AdminScreen({ products, setProducts, onBack }) {
  const [token, setToken] = useState(() => localStorage.getItem('nai-admin-token') || ''); const [orders, setOrders] = useState([]); const [form, setForm] = useState(null); const [login, setLogin] = useState({ email: 'admin@naitiaras.com', password: '' }); const [error, setError] = useState('')
  useEffect(() => { if (!token) return; fetch(`${API}/admin/orders`, { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.ok ? r.json() : Promise.reject()).then((data) => setOrders(data.orders || [])).catch(() => {}) }, [token])
  async function signIn(event) { event.preventDefault(); setError(''); try { const response = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); localStorage.setItem('nai-admin-token', data.token); setToken(data.token) } catch (reason) { setError(reason.message || 'Não foi possível entrar. Inicie o backend.') } }
  function logout() { localStorage.removeItem('nai-admin-token'); setToken('') }
  async function saveProduct(event) { event.preventDefault(); const body = { ...form, price: Number(form.price), stock: Number(form.stock), featured: Boolean(form.featured), status: form.status || 'active' }; const url = form.id ? `${API}/admin/products/${form.id}` : `${API}/admin/products`; const response = await fetch(url, { method: form.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) return setError(data.error || 'Não foi possível salvar o produto.'); setProducts((current) => form.id ? current.map((item) => item.id === data.product.id ? data.product : item) : [data.product, ...current]); setForm(null); setError('Produto salvo com sucesso.') }
  const updateForm = (key, value) => setForm((current) => ({ ...current, [key]: value }))
  if (!token) return <div className="admin-page"><div className="admin-login"><button className="back-link" onClick={onBack}>← Voltar para a loja</button><div className="admin-logo"><img src="/assets/logo.png" alt="Nai Tiaras" /></div><span className="section-kicker">Área restrita</span><h1>Gestão da loja</h1><p>Acesso exclusivo para a equipe da Nai Tiaras.</p><form onSubmit={signIn}><label>E-mail<input type="email" value={login.email} onChange={(event) => setLogin({ ...login, email: event.target.value })} required /></label><label>Senha<input type="password" value={login.password} onChange={(event) => setLogin({ ...login, password: event.target.value })} required /></label>{error && <div className="form-error">{error}</div>}<button className="primary-button full-button">Entrar <ArrowRight size={17} /></button></form></div></div>
  return <div className="admin-page"><header className="admin-header"><div className="shell header-inner"><a className="brand" href="#inicio"><img src="/assets/logo.png" alt="Nai Tiaras" /><span><strong>Nai</strong> Tiaras <small>gestão</small></span></a><div className="admin-header-actions"><button onClick={onBack}>Ver loja</button><button onClick={logout}><LogOut size={17} /> Sair</button></div></div></header><main className="shell admin-main"><div className="admin-title"><div><span className="section-kicker">Painel administrativo</span><h1>Olá, gestão.</h1><p>Atualize seu catálogo e acompanhe os pedidos.</p></div><button className="primary-button" onClick={() => setForm({ name: '', category: 'Laços', description: '', price: 0, sale_unit: 'unidade', stock: 0, image: '', status: 'active', featured: false })}><Plus size={17} /> Novo produto</button></div><div className="admin-stats"><div><Package size={19} /><span>Produtos ativos<strong>{products.filter((item) => item.status === 'active').length}</strong></span></div><div><ShoppingBag size={19} /><span>Itens no catálogo<strong>{products.length}</strong></span></div><div><Truck size={19} /><span>Pedidos recebidos<strong>{orders.length}</strong></span></div></div>{error && <div className="form-success">{error}</div>}<div className="admin-columns"><section className="admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Catálogo</span><h2>Seus produtos</h2></div><span>{products.length} itens</span></div><div className="admin-product-list">{products.map((item) => <div className="admin-product-row" key={item.id}><img src={item.image} alt="" /><div><strong>{item.name}</strong><small>{item.category} · {money(item.price)} / {unitLabel(item.sale_unit)}</small></div><span className={item.stock > 0 ? 'stock-ok' : 'stock-out'}>{item.stock} em estoque</span><button onClick={() => setForm({ ...item })} aria-label={`Editar ${item.name}`}><Pencil size={16} /></button></div>)}</div></section><section className="admin-card"><div className="admin-card-heading"><div><span className="section-kicker">Pedidos</span><h2>Acompanhe por aqui</h2></div></div>{orders.length === 0 ? <div className="admin-empty"><ShoppingBag size={25} /><p>Os pedidos feitos pelo site aparecerão aqui.</p></div> : <div className="orders-list">{orders.slice(0, 8).map((order) => <div className="order-row" key={order.id}><div><strong>#{order.order_number}</strong><small>{order.customer_name} · {money(order.total)}</small></div><span>{order.status}</span></div>)}</div>}</section></div></main>{form && <ProductForm form={form} updateForm={updateForm} onClose={() => setForm(null)} onSave={saveProduct} />}</div>
}

function ProductForm({ form, updateForm, onClose, onSave }) { function handleImage(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => updateForm('image', reader.result); reader.readAsDataURL(file) } return <div className="overlay"><div className="product-form"><div className="drawer-head"><div><span className="section-kicker">Catálogo</span><h2>{form.id ? 'Editar produto' : 'Novo produto'}</h2></div><button className="close-button" onClick={onClose}><X size={21} /></button></div><form onSubmit={onSave}><div className="form-grid"><label>Nome do produto<input required value={form.name} onChange={(event) => updateForm('name', event.target.value)} /></label><label>Categoria<select value={form.category} onChange={(event) => updateForm('category', event.target.value)}><option>Laços</option><option>Tiaras</option><option>Tiras de recém-nascido</option></select></label><label>Preço<input required type="number" min="0" step="0.01" value={form.price} onChange={(event) => updateForm('price', event.target.value)} /></label><label>Unidade de venda<select value={form.sale_unit} onChange={(event) => updateForm('sale_unit', event.target.value)}><option value="unidade">Unidade</option><option value="par">Par</option><option value="kit">Kit</option></select></label><label>Estoque<input required type="number" min="0" step="1" value={form.stock} onChange={(event) => updateForm('stock', event.target.value)} /></label><label>Status<select value={form.status} onChange={(event) => updateForm('status', event.target.value)}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></label></div><label>Descrição<textarea value={form.description} onChange={(event) => updateForm('description', event.target.value)} placeholder="Conte um pouco sobre a peça" /></label><label className="upload-field">Imagem do produto<input type="file" accept="image/*" onChange={handleImage} />{form.image && <img src={form.image} alt="Prévia do produto" />}</label><label className="check-field"><input type="checkbox" checked={Boolean(form.featured)} onChange={(event) => updateForm('featured', event.target.checked)} /> Destacar este produto na vitrine</label><button className="primary-button full-button">Salvar produto <Check size={17} /></button></form></div></div> }
